"""
RBAC / ABAC User Context
=========================
Carries authenticated user identity and access attributes into the pipeline.
The PolicyEngine uses this to filter data before it reaches the LLM.

MVP: Simulation mode — user context is supplied in the query request.
Future: Retrieved from Microsoft Entra ID / IBM Verify / Okta / Keycloak.

Architecture is ready for full enterprise identity integration:
  - Replace UserContext.__init__ with IDP token introspection
  - Policy rules reference user.roles, user.clearance, user.department
  - Data filter hooks in DatabaseConnector.execute_query() use user.data_filters
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any


@dataclass
class UserContext:
    """
    Authenticated user identity and access attributes.

    Current MVP behaviour (simulation mode):
      - user_id is taken from the API request body
      - roles / clearance / department are set to demo defaults
      - data_filters are empty (no row-level security applied)

    Enterprise integration points (future):
      - IDP token: Microsoft Entra ID, IBM Verify, Okta, Keycloak
      - Roles: retrieved from IDP group claims
      - Clearance: retrieved from LDAP/AD attribute
      - data_filters: generated by PolicyEngine based on roles + data classification
    """

    user_id:      str  = "anonymous"
    roles:        list[str] = field(default_factory=lambda: ["viewer"])
    department:   str  = "General"
    clearance:    str  = "public"        # public | internal | confidential | restricted
    groups:       list[str] = field(default_factory=list)
    project_ids:  list[str] = field(default_factory=list)

    # Data access filters (populated by PolicyEngine.build_data_filters())
    # Format: {"table_name": "WHERE clause string"}
    # Applied by DatabaseExecutionAgent before executing SQL
    data_filters: dict[str, str] = field(default_factory=dict)

    # IDP simulation fields (for demo)
    idp_provider: str  = "simulation"    # "entra_id" | "ibm_verify" | "okta" | "simulation"
    auth_method:  str  = "demo"          # "oauth2" | "saml" | "oidc" | "demo"
    mfa_verified: bool = False

    def can_access_classification(self, classification: str) -> bool:
        """
        Check if this user's clearance permits access to data of this classification.
        Clearance hierarchy: restricted > confidential > internal > public
        """
        hierarchy = ["public", "internal", "confidential", "restricted"]
        user_level = hierarchy.index(self.clearance) if self.clearance in hierarchy else 0
        required_level = hierarchy.index(classification) if classification in hierarchy else 0
        return user_level >= required_level

    def has_role(self, role: str) -> bool:
        return role in self.roles

    def to_dict(self) -> dict[str, Any]:
        return {
            "user_id":      self.user_id,
            "roles":        self.roles,
            "department":   self.department,
            "clearance":    self.clearance,
            "groups":       self.groups,
            "idp_provider": self.idp_provider,
            "auth_method":  self.auth_method,
            "mfa_verified": self.mfa_verified,
            "simulation_mode": self.idp_provider == "simulation",
        }

    @classmethod
    def demo_user(cls, user_id: str = "demo_user") -> "UserContext":
        return cls(
            user_id=user_id,
            roles=["analyst", "viewer"],
            department="Finance",
            clearance="confidential",
            idp_provider="simulation",
            auth_method="demo",
            mfa_verified=True,
        )

    @classmethod
    def admin_user(cls, user_id: str = "admin") -> "UserContext":
        return cls(
            user_id=user_id,
            roles=["admin", "analyst", "viewer"],
            department="IT",
            clearance="restricted",
            idp_provider="simulation",
            auth_method="demo",
            mfa_verified=True,
        )
